var Bucket = require('./util/bucket')

function Mika() {
    this.bucket              = new Bucket()
    this.constants           = require('./constants')
    this.getMatch            = require('./lib/getMatch')
    this.getPlayer           = require('./lib/players/getPlayer')
    this.getPlayerWL         = require('./lib/players/getPlayerWL')
    this.getPlayerMatches    = require('./lib/players/getPlayerMatches')
    this.getPlayerHeroes     = require('./lib/players/getPlayerHeroes')
    this.getPlayerPeers      = require('./lib/players/getPlayerPeers')
    this.getPlayerPros       = require('./lib/players/getPlayerPros')
    this.getPlayerRecords    = require('./lib/players/getPlayerRecords')
    this.getPlayerCounts     = require('./lib/players/getPlayerCounts')
    this.getPlayerHistograms = require('./lib/players/getPlayerHistograms')
    this.getPlayerWardmap    = require('./lib/players/getPlayerWardmap')
    this.getPlayerWordcloud  = require('./lib/players/getPlayerWordcloud')
    this.getPlayerRatings    = require('./lib/players/getPlayerRatings')
    this.getPlayerRankings   = require('./lib/players/getPlayerRankings')
    this.postPlayerRefresh   = require('./lib/players/postPlayerRefresh')
    this.getProPlayers       = require('./lib/getProPlayers')
    this.getProMatches       = require('./lib/getProMatches')
    this.getPublicMatches    = require('./lib/getPublicMatches')
    this.getHeroStats        = require('./lib/getHeroStats')
    this.getMetadata         = require('./lib/getMetadata')
    this.getDistributions    = require('./lib/getDistributions')
    this.search              = require('./lib/search')
    this.getRankings         = require('./lib/getRankings')
    this.getBenchmarks       = require('./lib/getBenchmarks')
    this.getStatus           = require('./lib/getStatus')
    this.getHealth           = require('./lib/getHealth')
    this.getByJobId          = require('./lib/request/getRequestByJobId')
    this.postByMatchId       = require('./lib/request/postRequestByMatchId')
    this.getHeroes           = require('./lib/getHeroes')
    this.getLeagues          = require('./lib/getLeagues')
    this.getReplays          = require('./lib/getReplays')
}

module.exports = Mika
